run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gosec
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning
      - name: error-return
        severity: error
      - name: error-naming
        severity: error
      - name: errorf
        severity: error

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
