# GoReleaser configuration for agentapiary
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod download

builds:
  - id: apiaryd
    main: ./cmd/apiaryd
    binary: apiaryd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: apiaryctl
    main: ./cmd/apiaryctl
    binary: apiaryctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: keeper
    main: ./cmd/keeper
    binary: keeper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - typo

release:
  github:
    owner: agentapiary
    name: apiary
  draft: false
  prerelease: auto
  name_template: "Release {{.Version}}"
  header: |
    ## What's New in {{ .Tag }}
    
    Full changelog below.
  footer: |
    ## Installation
    
    Download the appropriate binary for your OS and architecture from the assets below.
    
    ### Linux/macOS
    ```bash
    # Extract the archive
    tar -xzf apiary_*_Linux_x86_64.tar.gz
    
    # Move binaries to a location in your PATH
    sudo mv apiaryd apiaryctl keeper /usr/local/bin/
    ```
    
    ### Windows
    ```powershell
    # Extract the zip file
    # Add the directory to your PATH or move the .exe files to a directory in your PATH
    ```

# Uncomment if you want to publish to Homebrew
# brews:
#   - name: apiary
#     repository:
#       owner: agentapiary
#       name: homebrew-tap
#     folder: Formula
#     homepage: https://github.com/agentapiary/apiary
#     description: "Agent orchestration platform"
#     license: "Apache-2.0"
#     install: |
#       bin.install "apiaryd"
#       bin.install "apiaryctl"
#       bin.install "keeper"
