// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: api/proto/v1/apiary.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApiaryService_ListCells_FullMethodName       = "/apiary.v1.ApiaryService/ListCells"
	ApiaryService_GetCell_FullMethodName         = "/apiary.v1.ApiaryService/GetCell"
	ApiaryService_CreateCell_FullMethodName      = "/apiary.v1.ApiaryService/CreateCell"
	ApiaryService_UpdateCell_FullMethodName      = "/apiary.v1.ApiaryService/UpdateCell"
	ApiaryService_DeleteCell_FullMethodName      = "/apiary.v1.ApiaryService/DeleteCell"
	ApiaryService_ListAgentSpecs_FullMethodName  = "/apiary.v1.ApiaryService/ListAgentSpecs"
	ApiaryService_GetAgentSpec_FullMethodName    = "/apiary.v1.ApiaryService/GetAgentSpec"
	ApiaryService_CreateAgentSpec_FullMethodName = "/apiary.v1.ApiaryService/CreateAgentSpec"
	ApiaryService_UpdateAgentSpec_FullMethodName = "/apiary.v1.ApiaryService/UpdateAgentSpec"
	ApiaryService_DeleteAgentSpec_FullMethodName = "/apiary.v1.ApiaryService/DeleteAgentSpec"
	ApiaryService_ScaleAgentSpec_FullMethodName  = "/apiary.v1.ApiaryService/ScaleAgentSpec"
	ApiaryService_DrainAgentSpec_FullMethodName  = "/apiary.v1.ApiaryService/DrainAgentSpec"
	ApiaryService_ListHives_FullMethodName       = "/apiary.v1.ApiaryService/ListHives"
	ApiaryService_GetHive_FullMethodName         = "/apiary.v1.ApiaryService/GetHive"
	ApiaryService_CreateHive_FullMethodName      = "/apiary.v1.ApiaryService/CreateHive"
	ApiaryService_UpdateHive_FullMethodName      = "/apiary.v1.ApiaryService/UpdateHive"
	ApiaryService_DeleteHive_FullMethodName      = "/apiary.v1.ApiaryService/DeleteHive"
	ApiaryService_ScaleHive_FullMethodName       = "/apiary.v1.ApiaryService/ScaleHive"
	ApiaryService_ListSecrets_FullMethodName     = "/apiary.v1.ApiaryService/ListSecrets"
	ApiaryService_GetSecret_FullMethodName       = "/apiary.v1.ApiaryService/GetSecret"
	ApiaryService_CreateSecret_FullMethodName    = "/apiary.v1.ApiaryService/CreateSecret"
	ApiaryService_UpdateSecret_FullMethodName    = "/apiary.v1.ApiaryService/UpdateSecret"
	ApiaryService_DeleteSecret_FullMethodName    = "/apiary.v1.ApiaryService/DeleteSecret"
	ApiaryService_ListDrones_FullMethodName      = "/apiary.v1.ApiaryService/ListDrones"
	ApiaryService_GetDrone_FullMethodName        = "/apiary.v1.ApiaryService/GetDrone"
	ApiaryService_DeleteDrone_FullMethodName     = "/apiary.v1.ApiaryService/DeleteDrone"
	ApiaryService_GetDroneLogs_FullMethodName    = "/apiary.v1.ApiaryService/GetDroneLogs"
	ApiaryService_ExecDrone_FullMethodName       = "/apiary.v1.ApiaryService/ExecDrone"
	ApiaryService_DrainDrone_FullMethodName      = "/apiary.v1.ApiaryService/DrainDrone"
)

// ApiaryServiceClient is the client API for ApiaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiaryServiceClient interface {
	// Cells
	ListCells(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListCellsResponse, error)
	GetCell(ctx context.Context, in *GetCellRequest, opts ...grpc.CallOption) (*Cell, error)
	CreateCell(ctx context.Context, in *CreateCellRequest, opts ...grpc.CallOption) (*Cell, error)
	UpdateCell(ctx context.Context, in *UpdateCellRequest, opts ...grpc.CallOption) (*Cell, error)
	DeleteCell(ctx context.Context, in *DeleteCellRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// AgentSpecs
	ListAgentSpecs(ctx context.Context, in *ListAgentSpecsRequest, opts ...grpc.CallOption) (*ListAgentSpecsResponse, error)
	GetAgentSpec(ctx context.Context, in *GetAgentSpecRequest, opts ...grpc.CallOption) (*AgentSpec, error)
	CreateAgentSpec(ctx context.Context, in *CreateAgentSpecRequest, opts ...grpc.CallOption) (*AgentSpec, error)
	UpdateAgentSpec(ctx context.Context, in *UpdateAgentSpecRequest, opts ...grpc.CallOption) (*AgentSpec, error)
	DeleteAgentSpec(ctx context.Context, in *DeleteAgentSpecRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ScaleAgentSpec(ctx context.Context, in *ScaleAgentSpecRequest, opts ...grpc.CallOption) (*ScaleAgentSpecResponse, error)
	DrainAgentSpec(ctx context.Context, in *DrainAgentSpecRequest, opts ...grpc.CallOption) (*DrainAgentSpecResponse, error)
	// Hives
	ListHives(ctx context.Context, in *ListHivesRequest, opts ...grpc.CallOption) (*ListHivesResponse, error)
	GetHive(ctx context.Context, in *GetHiveRequest, opts ...grpc.CallOption) (*Hive, error)
	CreateHive(ctx context.Context, in *CreateHiveRequest, opts ...grpc.CallOption) (*Hive, error)
	UpdateHive(ctx context.Context, in *UpdateHiveRequest, opts ...grpc.CallOption) (*Hive, error)
	DeleteHive(ctx context.Context, in *DeleteHiveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ScaleHive(ctx context.Context, in *ScaleHiveRequest, opts ...grpc.CallOption) (*ScaleHiveResponse, error)
	// Secrets
	ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error)
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*Secret, error)
	CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*Secret, error)
	UpdateSecret(ctx context.Context, in *UpdateSecretRequest, opts ...grpc.CallOption) (*Secret, error)
	DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Drones
	ListDrones(ctx context.Context, in *ListDronesRequest, opts ...grpc.CallOption) (*ListDronesResponse, error)
	GetDrone(ctx context.Context, in *GetDroneRequest, opts ...grpc.CallOption) (*Drone, error)
	DeleteDrone(ctx context.Context, in *DeleteDroneRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetDroneLogs(ctx context.Context, in *GetDroneLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetDroneLogsResponse], error)
	ExecDrone(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecDroneRequest, ExecDroneResponse], error)
	DrainDrone(ctx context.Context, in *DrainDroneRequest, opts ...grpc.CallOption) (*DrainDroneResponse, error)
}

type apiaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApiaryServiceClient(cc grpc.ClientConnInterface) ApiaryServiceClient {
	return &apiaryServiceClient{cc}
}

func (c *apiaryServiceClient) ListCells(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListCellsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCellsResponse)
	err := c.cc.Invoke(ctx, ApiaryService_ListCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) GetCell(ctx context.Context, in *GetCellRequest, opts ...grpc.CallOption) (*Cell, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cell)
	err := c.cc.Invoke(ctx, ApiaryService_GetCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) CreateCell(ctx context.Context, in *CreateCellRequest, opts ...grpc.CallOption) (*Cell, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cell)
	err := c.cc.Invoke(ctx, ApiaryService_CreateCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) UpdateCell(ctx context.Context, in *UpdateCellRequest, opts ...grpc.CallOption) (*Cell, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cell)
	err := c.cc.Invoke(ctx, ApiaryService_UpdateCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) DeleteCell(ctx context.Context, in *DeleteCellRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ApiaryService_DeleteCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) ListAgentSpecs(ctx context.Context, in *ListAgentSpecsRequest, opts ...grpc.CallOption) (*ListAgentSpecsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentSpecsResponse)
	err := c.cc.Invoke(ctx, ApiaryService_ListAgentSpecs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) GetAgentSpec(ctx context.Context, in *GetAgentSpecRequest, opts ...grpc.CallOption) (*AgentSpec, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentSpec)
	err := c.cc.Invoke(ctx, ApiaryService_GetAgentSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) CreateAgentSpec(ctx context.Context, in *CreateAgentSpecRequest, opts ...grpc.CallOption) (*AgentSpec, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentSpec)
	err := c.cc.Invoke(ctx, ApiaryService_CreateAgentSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) UpdateAgentSpec(ctx context.Context, in *UpdateAgentSpecRequest, opts ...grpc.CallOption) (*AgentSpec, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentSpec)
	err := c.cc.Invoke(ctx, ApiaryService_UpdateAgentSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) DeleteAgentSpec(ctx context.Context, in *DeleteAgentSpecRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ApiaryService_DeleteAgentSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) ScaleAgentSpec(ctx context.Context, in *ScaleAgentSpecRequest, opts ...grpc.CallOption) (*ScaleAgentSpecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScaleAgentSpecResponse)
	err := c.cc.Invoke(ctx, ApiaryService_ScaleAgentSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) DrainAgentSpec(ctx context.Context, in *DrainAgentSpecRequest, opts ...grpc.CallOption) (*DrainAgentSpecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainAgentSpecResponse)
	err := c.cc.Invoke(ctx, ApiaryService_DrainAgentSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) ListHives(ctx context.Context, in *ListHivesRequest, opts ...grpc.CallOption) (*ListHivesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHivesResponse)
	err := c.cc.Invoke(ctx, ApiaryService_ListHives_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) GetHive(ctx context.Context, in *GetHiveRequest, opts ...grpc.CallOption) (*Hive, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hive)
	err := c.cc.Invoke(ctx, ApiaryService_GetHive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) CreateHive(ctx context.Context, in *CreateHiveRequest, opts ...grpc.CallOption) (*Hive, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hive)
	err := c.cc.Invoke(ctx, ApiaryService_CreateHive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) UpdateHive(ctx context.Context, in *UpdateHiveRequest, opts ...grpc.CallOption) (*Hive, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hive)
	err := c.cc.Invoke(ctx, ApiaryService_UpdateHive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) DeleteHive(ctx context.Context, in *DeleteHiveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ApiaryService_DeleteHive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) ScaleHive(ctx context.Context, in *ScaleHiveRequest, opts ...grpc.CallOption) (*ScaleHiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScaleHiveResponse)
	err := c.cc.Invoke(ctx, ApiaryService_ScaleHive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretsResponse)
	err := c.cc.Invoke(ctx, ApiaryService_ListSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Secret)
	err := c.cc.Invoke(ctx, ApiaryService_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Secret)
	err := c.cc.Invoke(ctx, ApiaryService_CreateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) UpdateSecret(ctx context.Context, in *UpdateSecretRequest, opts ...grpc.CallOption) (*Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Secret)
	err := c.cc.Invoke(ctx, ApiaryService_UpdateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ApiaryService_DeleteSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) ListDrones(ctx context.Context, in *ListDronesRequest, opts ...grpc.CallOption) (*ListDronesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDronesResponse)
	err := c.cc.Invoke(ctx, ApiaryService_ListDrones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) GetDrone(ctx context.Context, in *GetDroneRequest, opts ...grpc.CallOption) (*Drone, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Drone)
	err := c.cc.Invoke(ctx, ApiaryService_GetDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) DeleteDrone(ctx context.Context, in *DeleteDroneRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ApiaryService_DeleteDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiaryServiceClient) GetDroneLogs(ctx context.Context, in *GetDroneLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetDroneLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApiaryService_ServiceDesc.Streams[0], ApiaryService_GetDroneLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDroneLogsRequest, GetDroneLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApiaryService_GetDroneLogsClient = grpc.ServerStreamingClient[GetDroneLogsResponse]

func (c *apiaryServiceClient) ExecDrone(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecDroneRequest, ExecDroneResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApiaryService_ServiceDesc.Streams[1], ApiaryService_ExecDrone_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecDroneRequest, ExecDroneResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApiaryService_ExecDroneClient = grpc.BidiStreamingClient[ExecDroneRequest, ExecDroneResponse]

func (c *apiaryServiceClient) DrainDrone(ctx context.Context, in *DrainDroneRequest, opts ...grpc.CallOption) (*DrainDroneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainDroneResponse)
	err := c.cc.Invoke(ctx, ApiaryService_DrainDrone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiaryServiceServer is the server API for ApiaryService service.
// All implementations must embed UnimplementedApiaryServiceServer
// for forward compatibility.
type ApiaryServiceServer interface {
	// Cells
	ListCells(context.Context, *emptypb.Empty) (*ListCellsResponse, error)
	GetCell(context.Context, *GetCellRequest) (*Cell, error)
	CreateCell(context.Context, *CreateCellRequest) (*Cell, error)
	UpdateCell(context.Context, *UpdateCellRequest) (*Cell, error)
	DeleteCell(context.Context, *DeleteCellRequest) (*emptypb.Empty, error)
	// AgentSpecs
	ListAgentSpecs(context.Context, *ListAgentSpecsRequest) (*ListAgentSpecsResponse, error)
	GetAgentSpec(context.Context, *GetAgentSpecRequest) (*AgentSpec, error)
	CreateAgentSpec(context.Context, *CreateAgentSpecRequest) (*AgentSpec, error)
	UpdateAgentSpec(context.Context, *UpdateAgentSpecRequest) (*AgentSpec, error)
	DeleteAgentSpec(context.Context, *DeleteAgentSpecRequest) (*emptypb.Empty, error)
	ScaleAgentSpec(context.Context, *ScaleAgentSpecRequest) (*ScaleAgentSpecResponse, error)
	DrainAgentSpec(context.Context, *DrainAgentSpecRequest) (*DrainAgentSpecResponse, error)
	// Hives
	ListHives(context.Context, *ListHivesRequest) (*ListHivesResponse, error)
	GetHive(context.Context, *GetHiveRequest) (*Hive, error)
	CreateHive(context.Context, *CreateHiveRequest) (*Hive, error)
	UpdateHive(context.Context, *UpdateHiveRequest) (*Hive, error)
	DeleteHive(context.Context, *DeleteHiveRequest) (*emptypb.Empty, error)
	ScaleHive(context.Context, *ScaleHiveRequest) (*ScaleHiveResponse, error)
	// Secrets
	ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error)
	GetSecret(context.Context, *GetSecretRequest) (*Secret, error)
	CreateSecret(context.Context, *CreateSecretRequest) (*Secret, error)
	UpdateSecret(context.Context, *UpdateSecretRequest) (*Secret, error)
	DeleteSecret(context.Context, *DeleteSecretRequest) (*emptypb.Empty, error)
	// Drones
	ListDrones(context.Context, *ListDronesRequest) (*ListDronesResponse, error)
	GetDrone(context.Context, *GetDroneRequest) (*Drone, error)
	DeleteDrone(context.Context, *DeleteDroneRequest) (*emptypb.Empty, error)
	GetDroneLogs(*GetDroneLogsRequest, grpc.ServerStreamingServer[GetDroneLogsResponse]) error
	ExecDrone(grpc.BidiStreamingServer[ExecDroneRequest, ExecDroneResponse]) error
	DrainDrone(context.Context, *DrainDroneRequest) (*DrainDroneResponse, error)
	mustEmbedUnimplementedApiaryServiceServer()
}

// UnimplementedApiaryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiaryServiceServer struct{}

func (UnimplementedApiaryServiceServer) ListCells(context.Context, *emptypb.Empty) (*ListCellsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCells not implemented")
}
func (UnimplementedApiaryServiceServer) GetCell(context.Context, *GetCellRequest) (*Cell, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCell not implemented")
}
func (UnimplementedApiaryServiceServer) CreateCell(context.Context, *CreateCellRequest) (*Cell, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCell not implemented")
}
func (UnimplementedApiaryServiceServer) UpdateCell(context.Context, *UpdateCellRequest) (*Cell, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCell not implemented")
}
func (UnimplementedApiaryServiceServer) DeleteCell(context.Context, *DeleteCellRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCell not implemented")
}
func (UnimplementedApiaryServiceServer) ListAgentSpecs(context.Context, *ListAgentSpecsRequest) (*ListAgentSpecsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentSpecs not implemented")
}
func (UnimplementedApiaryServiceServer) GetAgentSpec(context.Context, *GetAgentSpecRequest) (*AgentSpec, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentSpec not implemented")
}
func (UnimplementedApiaryServiceServer) CreateAgentSpec(context.Context, *CreateAgentSpecRequest) (*AgentSpec, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgentSpec not implemented")
}
func (UnimplementedApiaryServiceServer) UpdateAgentSpec(context.Context, *UpdateAgentSpecRequest) (*AgentSpec, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgentSpec not implemented")
}
func (UnimplementedApiaryServiceServer) DeleteAgentSpec(context.Context, *DeleteAgentSpecRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAgentSpec not implemented")
}
func (UnimplementedApiaryServiceServer) ScaleAgentSpec(context.Context, *ScaleAgentSpecRequest) (*ScaleAgentSpecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScaleAgentSpec not implemented")
}
func (UnimplementedApiaryServiceServer) DrainAgentSpec(context.Context, *DrainAgentSpecRequest) (*DrainAgentSpecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainAgentSpec not implemented")
}
func (UnimplementedApiaryServiceServer) ListHives(context.Context, *ListHivesRequest) (*ListHivesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHives not implemented")
}
func (UnimplementedApiaryServiceServer) GetHive(context.Context, *GetHiveRequest) (*Hive, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHive not implemented")
}
func (UnimplementedApiaryServiceServer) CreateHive(context.Context, *CreateHiveRequest) (*Hive, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHive not implemented")
}
func (UnimplementedApiaryServiceServer) UpdateHive(context.Context, *UpdateHiveRequest) (*Hive, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHive not implemented")
}
func (UnimplementedApiaryServiceServer) DeleteHive(context.Context, *DeleteHiveRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHive not implemented")
}
func (UnimplementedApiaryServiceServer) ScaleHive(context.Context, *ScaleHiveRequest) (*ScaleHiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScaleHive not implemented")
}
func (UnimplementedApiaryServiceServer) ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedApiaryServiceServer) GetSecret(context.Context, *GetSecretRequest) (*Secret, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedApiaryServiceServer) CreateSecret(context.Context, *CreateSecretRequest) (*Secret, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSecret not implemented")
}
func (UnimplementedApiaryServiceServer) UpdateSecret(context.Context, *UpdateSecretRequest) (*Secret, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSecret not implemented")
}
func (UnimplementedApiaryServiceServer) DeleteSecret(context.Context, *DeleteSecretRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSecret not implemented")
}
func (UnimplementedApiaryServiceServer) ListDrones(context.Context, *ListDronesRequest) (*ListDronesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDrones not implemented")
}
func (UnimplementedApiaryServiceServer) GetDrone(context.Context, *GetDroneRequest) (*Drone, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDrone not implemented")
}
func (UnimplementedApiaryServiceServer) DeleteDrone(context.Context, *DeleteDroneRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDrone not implemented")
}
func (UnimplementedApiaryServiceServer) GetDroneLogs(*GetDroneLogsRequest, grpc.ServerStreamingServer[GetDroneLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetDroneLogs not implemented")
}
func (UnimplementedApiaryServiceServer) ExecDrone(grpc.BidiStreamingServer[ExecDroneRequest, ExecDroneResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecDrone not implemented")
}
func (UnimplementedApiaryServiceServer) DrainDrone(context.Context, *DrainDroneRequest) (*DrainDroneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainDrone not implemented")
}
func (UnimplementedApiaryServiceServer) mustEmbedUnimplementedApiaryServiceServer() {}
func (UnimplementedApiaryServiceServer) testEmbeddedByValue()                       {}

// UnsafeApiaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiaryServiceServer will
// result in compilation errors.
type UnsafeApiaryServiceServer interface {
	mustEmbedUnimplementedApiaryServiceServer()
}

func RegisterApiaryServiceServer(s grpc.ServiceRegistrar, srv ApiaryServiceServer) {
	// If the following call panics, it indicates UnimplementedApiaryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApiaryService_ServiceDesc, srv)
}

func _ApiaryService_ListCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).ListCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_ListCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).ListCells(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_GetCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).GetCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_GetCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).GetCell(ctx, req.(*GetCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_CreateCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).CreateCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_CreateCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).CreateCell(ctx, req.(*CreateCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_UpdateCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).UpdateCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_UpdateCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).UpdateCell(ctx, req.(*UpdateCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_DeleteCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).DeleteCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_DeleteCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).DeleteCell(ctx, req.(*DeleteCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_ListAgentSpecs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentSpecsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).ListAgentSpecs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_ListAgentSpecs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).ListAgentSpecs(ctx, req.(*ListAgentSpecsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_GetAgentSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).GetAgentSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_GetAgentSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).GetAgentSpec(ctx, req.(*GetAgentSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_CreateAgentSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).CreateAgentSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_CreateAgentSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).CreateAgentSpec(ctx, req.(*CreateAgentSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_UpdateAgentSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).UpdateAgentSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_UpdateAgentSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).UpdateAgentSpec(ctx, req.(*UpdateAgentSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_DeleteAgentSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).DeleteAgentSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_DeleteAgentSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).DeleteAgentSpec(ctx, req.(*DeleteAgentSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_ScaleAgentSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleAgentSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).ScaleAgentSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_ScaleAgentSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).ScaleAgentSpec(ctx, req.(*ScaleAgentSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_DrainAgentSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainAgentSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).DrainAgentSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_DrainAgentSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).DrainAgentSpec(ctx, req.(*DrainAgentSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_ListHives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHivesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).ListHives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_ListHives_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).ListHives(ctx, req.(*ListHivesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_GetHive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).GetHive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_GetHive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).GetHive(ctx, req.(*GetHiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_CreateHive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).CreateHive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_CreateHive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).CreateHive(ctx, req.(*CreateHiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_UpdateHive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).UpdateHive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_UpdateHive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).UpdateHive(ctx, req.(*UpdateHiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_DeleteHive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).DeleteHive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_DeleteHive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).DeleteHive(ctx, req.(*DeleteHiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_ScaleHive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleHiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).ScaleHive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_ScaleHive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).ScaleHive(ctx, req.(*ScaleHiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_ListSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).ListSecrets(ctx, req.(*ListSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_CreateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).CreateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_CreateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).CreateSecret(ctx, req.(*CreateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_UpdateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).UpdateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_UpdateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).UpdateSecret(ctx, req.(*UpdateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_DeleteSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).DeleteSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_DeleteSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).DeleteSecret(ctx, req.(*DeleteSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_ListDrones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDronesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).ListDrones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_ListDrones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).ListDrones(ctx, req.(*ListDronesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_GetDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).GetDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_GetDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).GetDrone(ctx, req.(*GetDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_DeleteDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).DeleteDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_DeleteDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).DeleteDrone(ctx, req.(*DeleteDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiaryService_GetDroneLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDroneLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiaryServiceServer).GetDroneLogs(m, &grpc.GenericServerStream[GetDroneLogsRequest, GetDroneLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApiaryService_GetDroneLogsServer = grpc.ServerStreamingServer[GetDroneLogsResponse]

func _ApiaryService_ExecDrone_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ApiaryServiceServer).ExecDrone(&grpc.GenericServerStream[ExecDroneRequest, ExecDroneResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApiaryService_ExecDroneServer = grpc.BidiStreamingServer[ExecDroneRequest, ExecDroneResponse]

func _ApiaryService_DrainDrone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainDroneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiaryServiceServer).DrainDrone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiaryService_DrainDrone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiaryServiceServer).DrainDrone(ctx, req.(*DrainDroneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiaryService_ServiceDesc is the grpc.ServiceDesc for ApiaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apiary.v1.ApiaryService",
	HandlerType: (*ApiaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCells",
			Handler:    _ApiaryService_ListCells_Handler,
		},
		{
			MethodName: "GetCell",
			Handler:    _ApiaryService_GetCell_Handler,
		},
		{
			MethodName: "CreateCell",
			Handler:    _ApiaryService_CreateCell_Handler,
		},
		{
			MethodName: "UpdateCell",
			Handler:    _ApiaryService_UpdateCell_Handler,
		},
		{
			MethodName: "DeleteCell",
			Handler:    _ApiaryService_DeleteCell_Handler,
		},
		{
			MethodName: "ListAgentSpecs",
			Handler:    _ApiaryService_ListAgentSpecs_Handler,
		},
		{
			MethodName: "GetAgentSpec",
			Handler:    _ApiaryService_GetAgentSpec_Handler,
		},
		{
			MethodName: "CreateAgentSpec",
			Handler:    _ApiaryService_CreateAgentSpec_Handler,
		},
		{
			MethodName: "UpdateAgentSpec",
			Handler:    _ApiaryService_UpdateAgentSpec_Handler,
		},
		{
			MethodName: "DeleteAgentSpec",
			Handler:    _ApiaryService_DeleteAgentSpec_Handler,
		},
		{
			MethodName: "ScaleAgentSpec",
			Handler:    _ApiaryService_ScaleAgentSpec_Handler,
		},
		{
			MethodName: "DrainAgentSpec",
			Handler:    _ApiaryService_DrainAgentSpec_Handler,
		},
		{
			MethodName: "ListHives",
			Handler:    _ApiaryService_ListHives_Handler,
		},
		{
			MethodName: "GetHive",
			Handler:    _ApiaryService_GetHive_Handler,
		},
		{
			MethodName: "CreateHive",
			Handler:    _ApiaryService_CreateHive_Handler,
		},
		{
			MethodName: "UpdateHive",
			Handler:    _ApiaryService_UpdateHive_Handler,
		},
		{
			MethodName: "DeleteHive",
			Handler:    _ApiaryService_DeleteHive_Handler,
		},
		{
			MethodName: "ScaleHive",
			Handler:    _ApiaryService_ScaleHive_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _ApiaryService_ListSecrets_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _ApiaryService_GetSecret_Handler,
		},
		{
			MethodName: "CreateSecret",
			Handler:    _ApiaryService_CreateSecret_Handler,
		},
		{
			MethodName: "UpdateSecret",
			Handler:    _ApiaryService_UpdateSecret_Handler,
		},
		{
			MethodName: "DeleteSecret",
			Handler:    _ApiaryService_DeleteSecret_Handler,
		},
		{
			MethodName: "ListDrones",
			Handler:    _ApiaryService_ListDrones_Handler,
		},
		{
			MethodName: "GetDrone",
			Handler:    _ApiaryService_GetDrone_Handler,
		},
		{
			MethodName: "DeleteDrone",
			Handler:    _ApiaryService_DeleteDrone_Handler,
		},
		{
			MethodName: "DrainDrone",
			Handler:    _ApiaryService_DrainDrone_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDroneLogs",
			Handler:       _ApiaryService_GetDroneLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecDrone",
			Handler:       _ApiaryService_ExecDrone_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/v1/apiary.proto",
}
